In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
!ls

Cap3_MedicionPobreza  drive  sample_data

In [4]:
!rm -rf Cap3_MedicionPobreza
!git clone https://github.com/LizamaD/Cap3_MedicionPobreza.git

Cloning into 'Cap3_MedicionPobreza'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 21 (delta 2), reused 21 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (21/21), 17.20 KiB | 17.20 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [5]:
import os
import pandas as pd

path_bases = "/content/drive/MyDrive/Doctorado_DavidLizama/datos_tesis/coneval/2024/Bases de datos/"
path_pobreza = '/content/drive/MyDrive/Doctorado_DavidLizama/datos_tesis/coneval/2024/Base final/pobreza_24.csv'

archivos = [
    'gastoshogar.csv',
    'concentradohogar.csv',
    'ingresos.csv',
    'trabajos.csv',
    'gastospersona.csv',
    'poblacion.csv',
    'hogares.csv',
    'viviendas.csv'
]

bases = {}

for archivo in archivos:
    ruta = os.path.join(path_bases, archivo)
    bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

/tmp/ipykernel_22317/3542550449.py:22: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/tmp/ipykernel_22317/3542550449.py:22: DtypeWarning: Columns (45,49,53,61,63,69,75,77,81,83,85) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/tmp/ipykernel_22317/3542550449.py:22: DtypeWarning: Columns (1,4,27,44) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

In [6]:
hogares = bases["hogares"]                     #'folioviv', 'foliohog'
poblacion = bases["poblacion"]                 #'folioviv', 'foliohog','numren'
ingresos = bases["ingresos"]                   #'folioviv', 'foliohog','numren'
viviendas = bases["viviendas"]                 #'folioviv'
gastoshogar = bases["gastoshogar"]             #'folioviv', 'foliohog'
concentradohogar = bases["concentradohogar"]   #'folioviv', 'foliohog'
gastospersona = bases["gastospersona"]         #'folioviv', 'foliohog','numren'
trabajos = bases["trabajos"]                   #'folioviv', 'foliohog','numren', 'id_trabajo'
pobreza = pd.read_csv(path_pobreza)            #'folioviv', 'foliohog','numren'

In [8]:
%cd /content/Cap3_MedicionPobreza

/content/Cap3_MedicionPobreza

In [9]:
from src.trabajos import process_trabajos
from src.ingresos import generar_ingreso_deflactado_ago2024
from src.gastoshogar import procesar_gastos_enigh
from src.gastospersona import procesar_gastos_persona_enigh
from src.hogares import process_hogares
from src.poblacion import process_poblacion
from src.viviendas import process_viviendas

In [18]:
pobreza.columns

Index(['folioviv', 'foliohog', 'numren', 'est_dis', 'upm', 'factor', 'tam_loc',
       'rururb', 'ent', 'ubica_geo', 'edad', 'sexo', 'parentesco', 'ic_rezedu',
       'anac_e', 'inas_esc', 'niv_ed', 'ic_asalud', 'ic_segsoc', 'sa_dir',
       'ss_dir', 's_salud', 'par', 'jef_ss', 'cony_ss', 'hijo_ss', 'pea',
       'jub', 'pam', 'ing_pam', 'ic_cv', 'icv_pisos', 'icv_muros',
       'icv_techos', 'icv_hac', 'ic_sbv', 'isb_agua', 'isb_dren', 'isb_luz',
       'isb_combus', 'ic_ali_nc', 'id_men', 'tot_iaad', 'tot_iamen', 'ins_ali',
       'ic_ali', 'lca', 'dch', 'plp_e', 'plp', 'pobreza', 'pobreza_e',
       'pobreza_m', 'vul_car', 'vul_ing', 'no_pobv', 'i_privacion',
       'carencias', 'carencias3', 'cuadrantes', 'prof1', 'prof_e1', 'profun',
       'int_pob', 'int_pobe', 'int_vulcar', 'int_caren', 'tamhogesc', 'ictpc',
       'ict', 'ing_mon', 'ing_lab', 'ing_ren', 'ing_tra', 'nomon', 'pago_esp',
       'reg_esp', 'hli', 'discap'],
      dtype='object')

In [19]:
pobreza[['folioviv','foliohog','numren','pobreza','pobreza_e']].head(2)

    folioviv  foliohog  numren  pobreza  pobreza_e
0  100001901         1       1      0.0        0.0
1  100001901         1       2      0.0        0.0

In [10]:
procesar_gastos_enigh(gastoshogar).head(2)

,folioviv,foliohog,gasto_tri,gas_nm_tri,imujer_tri,gasto_alimentos,gasto_salud,gasto_educacion,gasto_formal,gasto_tarjeta,factor,entidad,gasto_total,pct_gasto_alimentos
0,0100001901,1,39988.34,21214.25,1797.15,5078.52,0.0,1161.29,0.0,0.0,207,1,61202.59,0.082979
1,0100001902,1,36468.48,14184.32,996.60,11069.88,0.0,0.00,0.0,0.0,207,1,50652.80,0.218544

In [11]:
procesar_gastos_persona_enigh(gastospersona).head(2)

,folioviv,foliohog,numren,gasto_tri,gas_nm_tri,gasto_educ_total,gasto_salud_ind,inscrip,colegia,inst,factor,gasto_persona_total,tiene_gasto_educ
0,0100001901,1,01,0.00,20571.4,0.00,0.0,0.0,0.0,nan,207,20571.40,0
1,0100001901,1,03,7490.32,0.0,7490.32,0.0,0.0,2580.0,,207,7490.32,1

In [12]:
generar_ingreso_deflactado_ago2024(ingresos_df=ingresos, trabajo_df=trabajos).head(2)

/content/Cap3_MedicionPobreza/src/ingresos.py:34: FutureWarning: The provided callable <function sum at 0x7dcfc8708360> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  aguinaldo = pd.pivot_table(

    folioviv  foliohog       ing_mon       ing_lab  ing_ren  ing_tra
0  100001901         1  37549.466972  37549.466972      0.0      0.0
1  100001902         1  29422.556467  29422.556467      0.0      0.0

In [13]:
process_hogares(hogares).head(3)

,folioviv,foliohog,acc_alim1,acc_alim2,acc_alim3,acc_alim4,acc_alim5,acc_alim6,acc_alim7,acc_alim8,...,alim17_5_bin,alim17_6_bin,alim17_7_bin,alim17_8_bin,alim17_9_bin,alim17_10_bin,alim17_11_bin,alim17_12_bin,acc_alim18_bin,score_iaas
0,0100001901,1,2,2,2,2,2,2,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,0100001902,1,2,2,2,2,2,2,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,0100001904,1,1,2,1,1,2,2,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
process_poblacion(poblacion).head(2)

,folioviv,foliohog,numren,parentesco,edad,sexo,anios_esc,alfabetism,asis_esc,tiene_salud,segsoc,pob_discapacidad,etnia,hablaind,afrod,trabajo_mp,num_trabaj,score_trabajo_domestico,factor
0,0100001901,01,01,101,32,1,12.0,1.0,2.0,0,1.0,0,2.0,2.0,2,1,1,36.0,207
1,0100001901,01,02,201,24,2,15.0,1.0,2.0,0,2.0,0,2.0,2.0,2,1,1,36.0,207

In [15]:
process_viviendas(viviendas).head(2)

,folioviv,tipo_viv,tenencia,estim_pago,ratio_hacinamiento,ind_hacinamiento,carencia_piso,carencia_pared,carencia_techo,carencia_agua,carencia_drenaje,carencia_luz,carencia_combustible,score_vivienda_alta,tot_resid,tot_hog,factor
0,0100001901,7,1,0.0,4.000000,1,0,0,0,1,0,0,0,0,4,1,207
1,0100001902,1,3,4000.0,1.333333,0,0,0,0,1,0,0,0,0,4,1,207

In [16]:
process_trabajos(trabajos).head(2)

,folioviv,foliohog,numren,trapais,subor,indep,personal,pago,contrato,tipocontr,...,socios,soc_nr1,soc_nr2,soc_resp,otra_act,tipoact2,tipoact3,tipoact4,lugar,conf_pers
0,100001901,1,1,1,1,0,0,1,1,0,...,,,,,,,,,,
1,100001901,1,2,1,1,0,0,1,0,0,...,,,,,,,,,,