In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
!git clone https://github.com/LizamaD/Cap3_MedicionPobreza.git

fatal: destination path 'Cap3_MedicionPobreza' already exists and is not an empty directory.

In [1]:
import os
import pandas as pd

path_bases = "/content/drive/MyDrive/Doctorado_DavidLizama/datos_tesis/coneval/2024/Bases de datos/"
path_pobreza = '/content/drive/MyDrive/Doctorado_DavidLizama/datos_tesis/coneval/2024/Base final/pobreza_24.csv'

archivos = [
    'gastoshogar.csv',
    'concentradohogar.csv',
    'ingresos.csv',
    'trabajos.csv',
    'gastospersona.csv',
    'poblacion.csv',
    'hogares.csv',
    'viviendas.csv'
]

bases = {}

for archivo in archivos:
    ruta = os.path.join(path_bases, archivo)
    bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

/tmp/ipykernel_21345/3542550449.py:22: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/tmp/ipykernel_21345/3542550449.py:22: DtypeWarning: Columns (45,49,53,61,63,69,75,77,81,83,85) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/tmp/ipykernel_21345/3542550449.py:22: DtypeWarning: Columns (1,4,27,44) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

In [3]:
hogares = bases["hogares"]                     #'folioviv', 'foliohog'
poblacion = bases["poblacion"]                 #'folioviv', 'foliohog','numren'
ingresos = bases["ingresos"]                   #'folioviv', 'foliohog','numren'
viviendas = bases["viviendas"]                 #'folioviv'
gastoshogar = bases["gastoshogar"]             #'folioviv', 'foliohog'
concentradohogar = bases["concentradohogar"]   #'folioviv', 'foliohog'
gastospersona = bases["gastospersona"]         #'folioviv', 'foliohog','numren'
trabajos = bases["trabajos"]                   #'folioviv', 'foliohog','numren', 'id_trabajo'
pobreza = pd.read_csv(path_pobreza)                  #'folioviv', 'foliohog','numren'

In [4]:
from src.trabajos import process_trabajos
from src.ingresos import generar_ingreso_deflactado_ago2024
from src.gastoshogar import procesar_gastos_enigh
from src.gastospersona import procesar_gastos_persona_enigh
from src.hogares import process_hogares
from src.poblacion import process_poblacion
from src.viviendas import process_viviendas

ModuleNotFoundError: No module named 'src'

In [ ]:
procesar_gastos_enigh(gastoshogar).head(2)

In [ ]:
procesar_gastos_persona_enigh(gastospersona).head(2)

In [25]:
generar_ingreso_deflactado_ago2024(ingresos_df=ingresos, trabajo_df=trabajos).head(2)

/content/Cap3_MedicionPobreza/src/ingresos.py:34: FutureWarning: The provided callable <function sum at 0x7969c9318400> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  aguinaldo = pd.pivot_table(

    folioviv  foliohog       ing_mon       ing_lab  ing_ren  ing_tra
0  100001901         1  37549.466972  37549.466972      0.0      0.0
1  100001902         1  29422.556467  29422.556467      0.0      0.0

In [26]:
process_hogares(hogares).head(3)

,folioviv,foliohog,acc_alim1,acc_alim2,acc_alim3,acc_alim4,acc_alim5,acc_alim6,acc_alim7,acc_alim8,...,alim17_5_bin,alim17_6_bin,alim17_7_bin,alim17_8_bin,alim17_9_bin,alim17_10_bin,alim17_11_bin,alim17_12_bin,acc_alim18_bin,score_iaas
0,0100001901,1,2,2,2,2,2,2,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,0100001902,1,2,2,2,2,2,2,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,0100001904,1,1,2,1,1,2,2,1.0,2.0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
process_poblacion(poblacion).head(2)

,folioviv,foliohog,numren,parentesco,edad,sexo,anios_esc,alfabetism,asis_esc,tiene_salud,segsoc,pob_discapacidad,etnia,hablaind,afrod,trabajo_mp,num_trabaj,score_trabajo_domestico,factor
0,0100001901,01,01,101,32,1,12.0,1.0,2.0,0,1.0,0,2.0,2.0,2,1,1,36.0,207
1,0100001901,01,02,201,24,2,15.0,1.0,2.0,0,2.0,0,2.0,2.0,2,1,1,36.0,207

In [ ]:
process_trabajos(trabajos).head(2)

In [ ]:
process_viviendas(viviendas).head(2)