In [5]:
import os
import pandas as pd

path_bases = '/Users/davidlizama/Documents/modelos_tesis/Cap3_MedicionPobreza/data/raw'

archivos = [
    'gastoshogar.csv',
    'concentradohogar.csv',
    'ingresos.csv',
    'trabajos.csv',
    'gastospersona.csv',
    'poblacion.csv',
    'hogares.csv',
    'viviendas.csv',
    'pobreza_24.csv'
]

bases = {}

for archivo in archivos:
    ruta = os.path.join(path_bases, archivo)
    bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

/var/folders/mm/tts95r9s4lz3gddj693qwtnc0000gn/T/ipykernel_33744/1707603053.py:22: DtypeWarning: Columns (45) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/var/folders/mm/tts95r9s4lz3gddj693qwtnc0000gn/T/ipykernel_33744/1707603053.py:22: DtypeWarning: Columns (45,49,53,61,63,69,75,77,81,83,85) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)
/var/folders/mm/tts95r9s4lz3gddj693qwtnc0000gn/T/ipykernel_33744/1707603053.py:22: DtypeWarning: Columns (1,4,27,44) have mixed types. Specify dtype option on import or set low_memory=False.
  bases[archivo.replace(".csv", "")] = pd.read_csv(ruta)

In [6]:
hogares = bases["hogares"]                     #'folioviv', 'foliohog'
poblacion = bases["poblacion"]                 #'folioviv', 'foliohog','numren'
ingresos = bases["ingresos"]                   #'folioviv', 'foliohog','numren'
viviendas = bases["viviendas"]                 #'folioviv'
gastoshogar = bases["gastoshogar"]             #'folioviv', 'foliohog'
concentradohogar = bases["concentradohogar"]   #'folioviv', 'foliohog'
gastospersona = bases["gastospersona"]         #'folioviv', 'foliohog','numren'
trabajos = bases["trabajos"]                   #'folioviv', 'foliohog','numren', 'id_trabajo'
pobreza = bases["pobreza_24"]                  #'folioviv', 'foliohog','numren'

In [7]:
from trabajos import process_trabajos
from ingresos import generar_ingreso_deflactado_ago2024

ModuleNotFoundError: No module named 'trabajos'

In [18]:
import importlib
#import ingresos # o el modulo que hayas editado

# Esto fuerza a Python a leer el archivo actualizado desde Drive
#importlib.reload(ingresos) 
from ingresos import generar_ingreso_deflactado_ago2024
from viviendas import process_viviendas
from poblacion import process_poblacion
from hogares import process_hogares
from trabajos import process_trabajos

In [16]:
generar_ingreso_deflactado_ago2024(ingresos_df=ingresos, trabajo_df=trabajos).head(2)

/content/drive/MyDrive/Doctorado_DavidLizama/modelos_tesis/Cap3_MedicionPobreza/src/ingresos.py:34: FutureWarning: The provided callable <function sum at 0x7aae06db8900> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  aguinaldo = pd.pivot_table(

    folioviv  foliohog       ing_mon       ing_lab  ing_ren  ing_tra
0  100001901         1  37549.466972  37549.466972      0.0      0.0
1  100001902         1  29422.556467  29422.556467      0.0      0.0

In [19]:
process_hogares(hogares).head(3)

,folioviv,foliohog,huespedes,huesp_come,num_trab_d,trab_come,acc_alim1,acc_alim2,acc_alim3,acc_alim4,...,transferen,parto_g,negcua,est_alim,est_trans,bene_licon,otros_lts,diconsa,frec_dicon,otro_pago
0,100001901,1,0,,0,,2,2,2,2,...,2,2,2,5100,0,2,,2,NaN,
1,100001902,1,0,,0,,2,2,2,2,...,2,2,2,12000,0,2,,1,3.0,
2,100001904,1,0,,0,,1,2,1,1,...,2,2,2,4350,0,2,,2,NaN,

In [20]:
process_poblacion(poblacion).head(2)

,folioviv,foliohog,numren,noatenc_16,antec_esc,inscr_3,inscr_1,usotiempo6,motivo_aus,act_pnea2,...,mm_esp,hh_lug,min_4,hor_3,min_3,hor_4,hijos_sob,trabajo_mp,hijos_viv,hijos_mue
0,100001901,1,1,16.0,NaN,NaN,1.0,NaN,NaN,NaN,...,,,0,,,14,,1,,
1,100001901,1,2,16.0,NaN,3.0,NaN,NaN,NaN,NaN,...,,,0,,,7,2,1,2,0

In [21]:
process_trabajos(trabajos).head(2)

,folioviv,foliohog,numren,trapais,subor,indep,personal,pago,contrato,tipocontr,...,socios,soc_nr1,soc_nr2,soc_resp,otra_act,tipoact2,tipoact3,tipoact4,lugar,conf_pers
0,100001901,1,1,1,1,0,0,1,1,0,...,,,,,,,,,,
1,100001901,1,2,1,1,0,0,1,0,0,...,,,,,,,,,,

In [22]:
process_viviendas(viviendas).head(2)

,folioviv,tipo_viv,mat_pared,mat_techos,mat_pisos,antiguedad,antigua_ne,cocina,cocina_dor,cuart_dorm,...,p_pandeos,p_levanta,p_humedad,p_fractura,p_electric,p_tuberias,tot_resid,tot_hom,tot_muj,tot_hog
0,100001901,7,8,10,3,30,NaN,1,2.0,1,...,2,2,2,2,2,2,4,2,2,1
1,100001902,1,8,10,3,30,NaN,1,2.0,3,...,2,2,2,2,2,2,4,2,2,1